version: '3'

# 自己电脑:docker容器

services:
  micro-django-demo:
    build: .
    ports:
      - 20001:8000
    volumes:
      - .:/work
    environment:
      - DEBUG=true   # Python获取到后是个string类型
      - INIT_BUILD=true  # 首次执行时，需初始化数据库、表、表内初始数据，打开次设置。后续操作，无需设置次选项。
#      - REDIS_HOST=0.0.0.0  # 默认redis
      - DB_HOST=micro_mysql
      - DB_PORT=3306
      - DB_NAME=micro_django
      - DB_USER=root
      - DB_PWD=123456
#    command: ['python','manage.py', 'runserver', '0.0.0.0:8000']
    command: ['micro-django-start']
#    command:
#      - sleep
#      - "99999"
    networks:
      - django_demo_net

networks:
  django_demo_net:
    external: true