version: '3'

# 自己电脑:docker容器

services:
  django-demo:
    build: .
    ports:
      - 20001:8000
    volumes:
      - .:/work
    environment:
      - INIT_DB=true  # 首次执行时，需初始化数据库、表、表内初始数据，打开次设置。后续操作，无需设置次选项。
      - DEBUG=true   # Python获取到后是个string类型
#      - REDIS_HOST=0.0.0.0  # 默认redis
    command: ['python','manage.py', 'runserver', '0.0.0.0:8000']
#    command:
#      - sleep
#      - "99999"
    networks:
      - django_demo_net
    depends_on:
      - mysql
      - redis

networks:
  django_demo_net:
    external: true