version: '3'

services:
  django-demo:
    build: .
    ports:
      - 4444:8000
    volumes:
      - .:/work
    environment:
      - REDIS_HOST=0.0.0.0
      - DEBUG=true   # Python获取到后是个string类型
    command: ['python','manage.py', 'runserver', '0.0.0.0:8000']
#    command:
#      - sleep
#      - "99999"

  mysql:
    image: mysql:8.0.16
    ports:
      - 3306:3306
    restart: always


  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  adminer:
    image: adminer:4.6.2
    ports:
    - 8080:8080
    restart: always


networks:
  app_net:
    external: true