version: '3'

# 启动数据库相关容器
# 自己电脑:docker容器

services:
  micro_mysql:
    image: mysql:5.7.20
    ports:
      - 20012:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=micro_django
#    volumes:
#      - ./../_data_mysql:/var/lib/mysql
#      - ./../config_files/mysqlld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    # restart: always
    networks:
      - django_demo_net

  redis:
    image: redis:latest
    volumes:
      - ./../_data_redis:/data
      - ./../config_files/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 20013:6379
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    networks:
      - django_demo_net

  adminer:
    image: adminer:latest
    ports:
      - 20014:8080
    # restart: always
    networks:
      - django_demo_net


networks:
  django_demo_net:
    external: true