# Generated by Django 2.2.3 on 2019-07-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者们'},
        ),
        migrations.AlterModelOptions(
            name='authordetail',
            options={'verbose_name': '作者详情', 'verbose_name_plural': '作者们详情'},
        ),
    ]
